title: Notas em aberto
description: Um caderno sobre o que estou estudando e aprendendo.
url: https://pehprado.github.io
baseurl: ""
lang: pt-BR
timezone: America/Sao_Paulo
author:
  name: pehprado
  url: https://github.com/pehprado
markdown: kramdown
permalink: /notas/:title/
paginate: 5
paginate_path: /pagina/:num/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
sass:
  style: compressed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
